#pragma kernel SampleShadowMap
#pragma kernel SampleShadowCubeMap

struct ShadowData
{
    float3 pos;
    float3 normal;
    float2 uv;
    float shadowID;
};

Texture2D<float4> _ShadowMap;
Texture2D<float> _DepthMap;
AppendStructuredBuffer<ShadowData> _OutputBuffer;
RWStructuredBuffer<int> _DebugBuffer;

float4x4 _InvProjViewMatrix1;
float4x4 _InvProjViewMatrix2;
float4x4 _InvProjViewMatrix3;
float4x4 _InvProjViewMatrix4;
float4x4 _InvProjViewMatrix5;
float4x4 _InvProjViewMatrix6;
float _NearPlane;
float _FarPlane;
float _ShadowUVMultiplier;
int _RelativeUVSize;
int _AmountPixelsToSkipPerSample;
int _TextureSizeX;
int _TextureSizeY;

float remap(float value, float oldMin, float oldMax, float newMin, float newMax)
{
    float a = newMin + (value - oldMin) * (newMax - newMin);
    // a = a == 0 ? 0.1 : a;
    float b = (oldMax - oldMin);
    // b = b == 0 ? 0.1 : b;
    return a / b;
}

float3 CalculateWorldNormal(float3 pos1, float3 pos2, float3 pos3)
{
    float3 edge1 = pos2 - pos1;
    float3 edge2 = pos3 - pos1;
    float3 normal = cross(edge1, edge2);
    return normalize(normal);
}

float3 DepthToWorldPositionViewProj(float4x4 invProjViewMatrix, float2 screenUV, float depth)
{
    float2 ndcXY = screenUV * 2.0 - 1;
    float worldZDistance = _NearPlane + (depth * (_FarPlane - _NearPlane));
    float ndcZ = (worldZDistance - _NearPlane) * 2.0f / (_FarPlane - _NearPlane) - 1.0f;
    ndcZ *= -1;
    float4 ndcPos = float4(ndcXY.x, ndcXY.y, ndcZ, 1.0);
    float4 worldPos = mul(invProjViewMatrix, ndcPos);
    worldPos.xyz /= worldPos.w;
    
    return worldPos.xyz;
}

[numthreads(32,32,1)]
void SampleShadowMap (uint2 id : SV_DispatchThreadID)
{
    id *= _AmountPixelsToSkipPerSample;
    float4 shadow = _ShadowMap[id];
    float depth = _DepthMap[id];
    
    if (depth > 0 && shadow.r > 0)
    {
        InterlockedAdd(_DebugBuffer[0], 1);
        float depthX = _DepthMap[id + uint2(1, 0)];
        float depthY = _DepthMap[id + uint2(0, 1)];
        float2 uv = float2((float)id.x / _TextureSizeX, (float)id.y / _TextureSizeY);
        float3 worldPos = DepthToWorldPositionViewProj(_InvProjViewMatrix1, uv, depth);
        float3 worldPosX = DepthToWorldPositionViewProj(_InvProjViewMatrix1, uv + float2(1.0 / _TextureSizeX, 0), depthX);
        float3 worldPosY = DepthToWorldPositionViewProj(_InvProjViewMatrix1, uv + float2(0, 1.0 / _TextureSizeY), depthY);

        ShadowData shadowData;
        shadowData.pos = worldPos;
        shadowData.normal = CalculateWorldNormal(worldPos, worldPosY, worldPosX);
        shadowData.shadowID = shadow.r;

        //Particle UV
        float shadowSize = _RelativeUVSize == 1 ? shadow.a : 1;
        shadowSize *= _ShadowUVMultiplier;
        float2 shadowUVX = float2(shadow.g - shadowSize, shadow.g + shadowSize);
        float2 shadowUVY = float2(shadow.b - shadowSize, shadow.b + shadowSize);
        float2 shadowUV = float2(remap(uv.x, shadowUVX.x, shadowUVX.y, 0, 1), remap(uv.y, shadowUVY.x, shadowUVY.y, 0, 1));
        shadowData.uv = shadowUV;
        
        _OutputBuffer.Append(shadowData);
    }
}

[numthreads(32,32,1)]
void SampleShadowCubeMap (uint2 id : SV_DispatchThreadID)
{
    id *= _AmountPixelsToSkipPerSample;
    float4 shadow = _ShadowMap[id];
    float depth = _DepthMap[id];
    
    if (depth > 0 && shadow.r > 0)
    {
        InterlockedAdd(_DebugBuffer[0], 1);
        float depthX = _DepthMap[id + uint2(1, 0)];
        float depthY = _DepthMap[id + uint2(0, 1)];
        int faceIndex = floor(id.x / (_TextureSizeX / 6));
        float2 uv = float2((float)id.x / _TextureSizeX, (float)id.y / _TextureSizeY);
        uv.x = remap(uv.x, 1/6.0 * faceIndex, 1/6.0 * (faceIndex + 1), 0, 1);
        
        float3 worldPos;
        float3 worldPosX;
        float3 worldPosY;
        
        switch (faceIndex)
        {
        case 0 :
            worldPos = DepthToWorldPositionViewProj(_InvProjViewMatrix1, uv, depth);
            worldPosX = DepthToWorldPositionViewProj(_InvProjViewMatrix1, uv + float2(1.0 / _TextureSizeX, 0), depthX);
            worldPosY = DepthToWorldPositionViewProj(_InvProjViewMatrix1, uv + float2(0, 1.0 / _TextureSizeY), depthY);
            break;
        case 1 :
            worldPos = DepthToWorldPositionViewProj(_InvProjViewMatrix2, uv, depth);
            worldPosX = DepthToWorldPositionViewProj(_InvProjViewMatrix2, uv + float2(1.0 / _TextureSizeX, 0), depthX);
            worldPosY = DepthToWorldPositionViewProj(_InvProjViewMatrix2, uv + float2(0, 1.0 / _TextureSizeY), depthY);
            break;
        case 2 :
            worldPos = DepthToWorldPositionViewProj(_InvProjViewMatrix3, uv, depth);
            worldPosX = DepthToWorldPositionViewProj(_InvProjViewMatrix3, uv + float2(1.0 / _TextureSizeX, 0), depthX);
            worldPosY = DepthToWorldPositionViewProj(_InvProjViewMatrix3, uv + float2(0, 1.0 / _TextureSizeY), depthY);
            break;
        case 3 :
            worldPos = DepthToWorldPositionViewProj(_InvProjViewMatrix4, uv, depth);
            worldPosX = DepthToWorldPositionViewProj(_InvProjViewMatrix4, uv + float2(1.0 / _TextureSizeX, 0), depthX);
            worldPosY = DepthToWorldPositionViewProj(_InvProjViewMatrix4, uv + float2(0, 1.0 / _TextureSizeY), depthY);
            break;
        case 4 :
            worldPos = DepthToWorldPositionViewProj(_InvProjViewMatrix5, uv, depth);
            worldPosX = DepthToWorldPositionViewProj(_InvProjViewMatrix5, uv + float2(1.0 / _TextureSizeX, 0), depthX);
            worldPosY = DepthToWorldPositionViewProj(_InvProjViewMatrix5, uv + float2(0, 1.0 / _TextureSizeY), depthY);
            break;
        case 5 :
            worldPos = DepthToWorldPositionViewProj(_InvProjViewMatrix6, uv, depth);
            worldPosX = DepthToWorldPositionViewProj(_InvProjViewMatrix6, uv + float2(1.0 / _TextureSizeX, 0), depthX);
            worldPosY = DepthToWorldPositionViewProj(_InvProjViewMatrix6, uv + float2(0, 1.0 / _TextureSizeY), depthY);
            break;
        default:
            break;
        }

        ShadowData shadowData;
        shadowData.pos = worldPos;
        shadowData.normal = CalculateWorldNormal(worldPos, worldPosY, worldPosX);
        float shadowSize = _RelativeUVSize == 1 ? shadow.a : 1;
        shadowSize *= _ShadowUVMultiplier;
        float2 shadowUVX = float2(shadow.g - shadowSize, shadow.g + shadowSize);
        float2 shadowUVY = float2(shadow.b - shadowSize, shadow.b + shadowSize);
        float2 shadowUV = float2(remap(uv.x, shadowUVX.x, shadowUVX.y, 0, 1), remap(uv.y, shadowUVY.x, shadowUVY.y, 0, 1));
        shadowData.uv = shadowUV;
        shadowData.shadowID = shadow.r;
        _OutputBuffer.Append(shadowData);
    }
}
