#pragma kernel Blur1
#pragma kernel Blur2
#pragma kernel SampleShadowMap
#pragma kernel SampleShadowCubeMap

#include "PackCustomShadowValues.hlsl"
#include "CustomShadowsLibrary.hlsl"

struct ShadowData
{
    float3 pos;
    float3 normal;
    float2 uv;
    float shadowID;
};

Texture2D<float2> _ShadowMap;
Texture2D<half> _DepthMap;
AppendStructuredBuffer<ShadowData> _OutputBuffer;

float4x4 _InvProjViewMatrix0;
float4x4 _InvProjViewMatrix1;
float4x4 _InvProjViewMatrix2;
float4x4 _InvProjViewMatrix3;
float4x4 _InvProjViewMatrix4;
float4x4 _InvProjViewMatrix5;
float _NearPlane;
float _FarPlane;
float _ShadowUVMultiplier;
int _RelativeUVSize;
int _AmountPixelsToSkipPerSampleX;
int _AmountPixelsToSkipPerSampleY;
int _ShadowUVMinPosX, _ShadowUVMinPosY, _ShadowUVMaxPosX, _ShadowUVMaxPosY, _ShadowMapSizeX, _ShadowMapSizeY;

int sampleSize;

[numthreads(32,32,1)] 
void SampleShadowMap (uint2 id : SV_DispatchThreadID)
{
    id *= uint2(_AmountPixelsToSkipPerSampleX, _AmountPixelsToSkipPerSampleY);
    float2 shadow = _ShadowMap[id];
    float depth = _DepthMap[id];
    int shadowID = GetShadowID(shadow);
    float2 shadowUVPos = GetShadowUVPos(shadow);
    float shadowUVSize = GetShadowUVSize(shadow);

    //the + 1 for id is to check if the depthX will not be out of bounds
    if (depth == 0 || shadowID == 0 || id.x + 1 > _ShadowUVMaxPosX || id.y + 1 > _ShadowUVMaxPosY)
        return;

    float depthX = _DepthMap[id + uint2(1, 0)];
    float depthY = _DepthMap[id + uint2(0, 1)];
    float2 uv = float2((float)(id.x - _ShadowUVMinPosX) / _ShadowMapSizeX, (float)(id.y - _ShadowUVMinPosY) / _ShadowMapSizeY);
    float3 worldPos = DepthToWorldPositionViewProj(_InvProjViewMatrix0, uv, _NearPlane, _FarPlane, depth);
    float3 worldPosX = DepthToWorldPositionViewProj(_InvProjViewMatrix0, uv + float2(1.0 / _ShadowMapSizeX, 0), _NearPlane, _FarPlane, depthX);
    float3 worldPosY = DepthToWorldPositionViewProj(_InvProjViewMatrix0, uv + float2(0, 1.0 / _ShadowMapSizeY), _NearPlane, _FarPlane, depthY);

    ShadowData shadowData;
    shadowData.pos = worldPos;
    shadowData.normal = CalculateWorldNormal(worldPos, worldPosY, worldPosX);
    shadowData.shadowID = shadowID;

    //Particle UV
    float shadowSize = _RelativeUVSize == 1 ? shadowUVSize : 1;
    shadowSize *= _ShadowUVMultiplier;
    float2 shadowUVX = float2(shadowUVPos.x - shadowSize, shadowUVPos.x + shadowSize);
    float2 shadowUVY = float2(shadowUVPos.y - shadowSize, shadowUVPos.y + shadowSize);
    float2 shadowUV = float2(remap(uv.x, shadowUVX.x, shadowUVX.y, 0, 1), remap(uv.y, shadowUVY.x, shadowUVY.y, 0, 1));
    shadowData.uv = shadowUV;
        
    _OutputBuffer.Append(shadowData);
}

[numthreads(32,32,1)]
void SampleShadowCubeMap (uint2 id : SV_DispatchThreadID)
{
    id *= uint2(_AmountPixelsToSkipPerSampleX, _AmountPixelsToSkipPerSampleY);
    float2 shadow = _ShadowMap[id];
    float depth = _DepthMap[id];
    uint shadowID = GetShadowID(shadow);
    float2 shadowUVPos = GetShadowUVPos(shadow);
    float shadowUVSize = GetShadowUVSize(shadow);

    //the + 1 for id is to check if the depthX will not be out of bounds
    if (depth == 0 || shadowID == 0 || id.x + 1 > _ShadowUVMaxPosX || id.y + 1 > _ShadowUVMaxPosY)
        return;

    float depthX = _DepthMap[id + uint2(1, 0)];
    float depthY = _DepthMap[id + uint2(0, 1)];
    int faceIndex = floor(((id.x - _ShadowUVMinPosX) / (float)_ShadowMapSizeX) * 3) + floor(((id.y - _ShadowUVMinPosY) / (float)_ShadowMapSizeY) * 2) * 3;
    float2 uv = float2((float)(id.x - _ShadowUVMinPosX) / (float)_ShadowMapSizeX, (float)(id.y - _ShadowUVMinPosY) / (float)_ShadowMapSizeY);
    uv = GetLocalCubeMapUV(uv);
    
    float3 worldPos;
    float3 worldPosX;
    float3 worldPosY;

    switch (faceIndex)
    {
    case 0 :
        worldPos = DepthToWorldPositionViewProj(_InvProjViewMatrix0, uv, _NearPlane, _FarPlane, depth);
        worldPosX = DepthToWorldPositionViewProj(_InvProjViewMatrix0, uv + float2(1.0 / _ShadowMapSizeX, 0), _NearPlane, _FarPlane, depthX);
        worldPosY = DepthToWorldPositionViewProj(_InvProjViewMatrix0, uv + float2(0, 1.0 / _ShadowMapSizeY), _NearPlane, _FarPlane, depthY);
        break;
    case 1 :
        worldPos = DepthToWorldPositionViewProj(_InvProjViewMatrix1, uv, _NearPlane, _FarPlane, depth);
        worldPosX = DepthToWorldPositionViewProj(_InvProjViewMatrix1, uv + float2(1.0 / _ShadowMapSizeX, 0), _NearPlane, _FarPlane, depthX);
        worldPosY = DepthToWorldPositionViewProj(_InvProjViewMatrix1, uv + float2(0, 1.0 / _ShadowMapSizeY), _NearPlane, _FarPlane, depthY);
        break;
    case 2 :
        worldPos = DepthToWorldPositionViewProj(_InvProjViewMatrix2, uv, _NearPlane, _FarPlane, depth);
        worldPosX = DepthToWorldPositionViewProj(_InvProjViewMatrix2, uv + float2(1.0 / _ShadowMapSizeX, 0), _NearPlane, _FarPlane, depthX);
        worldPosY = DepthToWorldPositionViewProj(_InvProjViewMatrix2, uv + float2(0, 1.0 / _ShadowMapSizeY), _NearPlane, _FarPlane, depthY);
        break;
    case 3 :
        worldPos = DepthToWorldPositionViewProj(_InvProjViewMatrix3, uv, _NearPlane, _FarPlane, depth);
        worldPosX = DepthToWorldPositionViewProj(_InvProjViewMatrix3, uv + float2(1.0 / _ShadowMapSizeX, 0), _NearPlane, _FarPlane, depthX);
        worldPosY = DepthToWorldPositionViewProj(_InvProjViewMatrix3, uv + float2(0, 1.0 / _ShadowMapSizeY), _NearPlane, _FarPlane, depthY);
        break;
    case 4 :
        worldPos = DepthToWorldPositionViewProj(_InvProjViewMatrix4, uv, _NearPlane, _FarPlane, depth);
        worldPosX = DepthToWorldPositionViewProj(_InvProjViewMatrix4, uv + float2(1.0 / _ShadowMapSizeX, 0), _NearPlane, _FarPlane, depthX);
        worldPosY = DepthToWorldPositionViewProj(_InvProjViewMatrix4, uv + float2(0, 1.0 / _ShadowMapSizeY), _NearPlane, _FarPlane, depthY);
        break;
    case 5 :
        worldPos = DepthToWorldPositionViewProj(_InvProjViewMatrix5, uv, _NearPlane, _FarPlane, depth);
        worldPosX = DepthToWorldPositionViewProj(_InvProjViewMatrix5, uv + float2(1.0 / _ShadowMapSizeX, 0), _NearPlane, _FarPlane, depthX);
        worldPosY = DepthToWorldPositionViewProj(_InvProjViewMatrix5, uv + float2(0, 1.0 / _ShadowMapSizeY), _NearPlane, _FarPlane, depthY);
        break;
    default:
        break;
    }

    ShadowData shadowData;
    shadowData.pos = worldPos;
    shadowData.normal = CalculateWorldNormal(worldPos, worldPosY, worldPosX);
    shadowData.shadowID = shadowID;

    //Particle UV
    float shadowSize = _RelativeUVSize == 1 ? shadowUVSize : 1;
    shadowSize *= _ShadowUVMultiplier;
    float2 shadowUVX = float2(shadowUVPos.x - shadowSize, shadowUVPos.x + shadowSize);
    float2 shadowUVY = float2(shadowUVPos.y - shadowSize, shadowUVPos.y + shadowSize);
    float2 shadowUV = float2(remap(uv.x, shadowUVX.x, shadowUVX.y, 0, 1), remap(uv.y, shadowUVY.x, shadowUVY.y, 0, 1));
    shadowData.uv = shadowUV;
        
    _OutputBuffer.Append(shadowData);
}

[numthreads(32,32,1)]
void Blur1 (uint2 id : SV_DispatchThreadID)
{
    // float2 output = _ShadowAtlas[id];
    // float average = 0;
    //
    // for (int i = -sampleSize; i <= sampleSize; ++i)
    // {
    //     for (int j = -sampleSize; j <= sampleSize; ++j)
    //     {
    //         float2 tempOutput = _ShadowAtlas[id + uint2(i, j)];
    //         average += saturate(ceil(GetShadowID(tempOutput)));
    //     }
    // }
    // average /= sampleSize * sampleSize * 6;
    // average = saturate(average);
    //
    // if (GetShadowID(output) > 0)
    // {
    //     _ShadowAtlas[id] = SetBlur(output, average);
    // }
}

[numthreads(32,32,1)]
void Blur2 (uint2 id : SV_DispatchThreadID)
{
    // float2 output = _ShadowAtlas[id];
    // float average = 0;
    // for (int i = -sampleSize; i <= sampleSize; ++i)
    // {
    //     average += _ShadowAtlas[id + uint2(0, i)].b;
    // }
    // average /= sampleSize * 2 + 1;
    // if (UnpackFloatTo2Half(output.r).r > 0)
    // {
    //     output.a = (average - 0.5) * 2;
    // }
    // else
    // {
    //     output.a = 0;
    // }
    // // output.a = average;
    //
    // _ShadowAtlas[id] = output;
}

