#pragma kernel SampleShadowMap
#pragma kernel SampleShadowCubeMap

Texture2D<float4> _ShadowMap;
Texture2D<float> _DepthMap;
float4x4 _InvProjViewMatrix;
AppendStructuredBuffer<float3> _OutputBuffer;
RWStructuredBuffer<int> _DebugBuffer;

float _NearPlane;
float _FarPlane;
int _AmountPixelsToSkipPerSample;
int _TextureSizeX;
int _TextureSizeY;

float3 DepthToWorldPositionViewProj(float4x4 invProjViewMatrix, float2 screenUV, float depth)
{
    // Convert screen UV to NDC
    float2 ndcXY = screenUV * 2.0 - 1;
    
    // Create NDC position
    float worldZDistance = _NearPlane + (depth * (_FarPlane - _NearPlane));
    float ndcZ = ((worldZDistance - _NearPlane) * 2.0f / (_FarPlane - _NearPlane)) - 1.0f;
    ndcZ *= -1;
    float4 ndcPos = float4(ndcXY.x, ndcXY.y, ndcZ, 1.0);
    
    // Transform directly from NDC to world space
    float4 worldPos = mul(invProjViewMatrix, ndcPos);
    
    // Perspective divide
    worldPos.xyz /= worldPos.w;
    
    return worldPos.xyz;
}

[numthreads(32,32,1)]
void SampleShadowMap (uint2 id : SV_DispatchThreadID)
{
    id *= _AmountPixelsToSkipPerSample;
    float4 shadow = _ShadowMap[id];
    float depth = _DepthMap[id];
    if (depth > 0 && shadow.r > 0)
    {
        InterlockedAdd(_DebugBuffer[0], 1);
        float2 uv = float2((float)id.x / _TextureSizeX, (float)id.y / _TextureSizeY);
        _OutputBuffer.Append(DepthToWorldPositionViewProj(_InvProjViewMatrix, uv, depth));
    }
}

[numthreads(32,32,1)]
void SampleShadowCubeMap (uint2 id : SV_DispatchThreadID)
{
    id *= _AmountPixelsToSkipPerSample;
    float4 shadow = _ShadowMap[id];
    float depth = _DepthMap[id];
    if (depth > 0 && shadow.r > 0)
    {
        InterlockedAdd(_DebugBuffer[0], 1);
        float2 uv = float2(id.x / 2048.0, id.y / 2048.0);
        _OutputBuffer.Append(DepthToWorldPositionViewProj(_InvProjViewMatrix, uv, depth));
    }
}
